
services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - traefik-network
    environment:
      - "POSTGRES_USER=metabase"
      # - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=Welc0me123"
      # - "PGDATA=/var/lib/postgresql/data"
    # volumes:
    # - c:/docker/metabase/pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    #ports:
    # - 3500:3500
    networks:
      - traefik-network
    volumes:
      - e:/docker-images-data/metabase/plugins:/plugins
      - e:/docker-images-data/metabase-data:/metabase-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.entrypoints=insecure"
      - "traefik.http.routers.metabase.rule=Host(`metabase.docker.localhost`)"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
        # - "traefik.http.routers.metabase.tls.certresolver=le"
    environment:
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=Welc0me123"
      - "MB_DB_HOST=postgres-db"
    depends_on:
      - postgres-db
    links:
      - postgres-db

networks:
  traefik-network:
    external: true
