services:
  #base
  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb
  photoprism:
    extends:
      file: docker-compose.services.yml
      service: photoprism

#networks
networks:
  proxy:
    external: true
