services:
  #base
  traefik:
    extends:
      file: docker-compose.base.yml
      service: traefik
  adguardhome:
    extends:
      file: docker-compose.base.yml
      service: adguardhome
  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb
  mssql:
    extends:
      file: docker-compose.base.yml
      service: mssql
  postgres-db:
    extends:
      file: docker-compose.base.yml
      service: postgres-db
  portainer:
    extends:
      file: docker-compose.base.yml
      service: portainer
  #services
  actualbudget:
    extends:
      file: docker-compose.services.yml
      service: actualbudget
  photoprism:
    extends:
      file: docker-compose.services.yml
      service: photoprism
  transmission:
    extends:
      file: docker-compose.services.yml
      service: transmission
  plex:
    extends:
      file: docker-compose.services.yml
      service: plex
  radarr:
    extends:
      file: docker-compose.services.yml
      service: radarr
  airsonic:
    extends:
      file: docker-compose.services.yml
      service: airsonic
  metabase:
    extends:
      file: docker-compose.services.yml
      service: metabase
  jira:
    extends:
      file: docker-compose.services.yml
      service: jira
#networks
networks:
  proxy:
    external: true
