services:
  thunderbird:
    image: jlesage/thunderbird
    pull_policy: always
    container_name: thunderbird
    ports:
      - "5800:5800"
    volumes:
      - "${BASE_PATH}/thunderbird:/config:rw"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thunderbird.entrypoints=web"
      - "traefik.http.routers.thunderbird.rule=Host(`email.local`)"
      - "traefik.http.services.thunderbird.loadbalancer.server.port=5800"

networks:
  proxy:
    external: true
