version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "4080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "prasannaraja@msn.com"
      PGADMIN_DEFAULT_PASSWORD: "sasa@123"
    restart: always
