---
version: "2"
services:
  airsonic:
    image: lscr.io/linuxserver/airsonic
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # - CONTEXT_PATH=URL_BASE #optional
      # - JAVA_OPTS=options #optional
    volumes:
      - ./config:/config
      - $MUSIC_FOLDER:/music
      - $PLAYLIST_FOLDER:/playlists
      - $PODCAST_FOLDER:/podcasts
      # - /path/to/other media:/media #optional
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.entrypoints=web"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.local`)"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
        # - "traefik.http.routers.airsonic.tls.certresolver=le"

networks:
  proxy:
    external: true
