services:
  #databases
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: always
    container_name: mssql
    volumes:
      - ${BASE_PATH}/mssql/data:/var/opt/mssql/data
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=sasa@123"
    ports:
      - "1401:1433"
    networks:
      - proxy

  mongodb:
    image: mongo
    container_name: mongodb
    pull_policy: always
    ports:
      - "27017:27017"
    networks:
      - proxy
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin@123"

  postgres:
    image: postgres
    container_name: postgres
    pull_policy: always
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    networks:
      - proxy
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  proxy:
    external: true
