version: '3.5'

services:
  api:
    build: ../ApiGateway/Ocelot
    container_name: api
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - network-gateway
      - network-microservice
    links:
      - users_service
      - movies_service
      - reviews_service
      - consul
    depends_on:
      - consul
