version: "3.8"

services:
  traefik:
    image: traefik:latest # Use the latest stable version of Traefik
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable the Traefik dashboard (insecure mode, for development only)
      - "--providers.docker=true" # Enable Docker as a provider
      - "--entrypoints.web.address=:80" # Define the entrypoint for HTTP
      - "--entrypoints.websecure.address=:443" # Define the entrypoint for HTTPS
    ports:
      - "80:80" # Expose port 80 for HTTP
      - "443:443" # Expose port 443 for HTTPS
      - "8080:8080" # Expose port 8080 for the Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Mount Docker socket to allow Traefik to interact with the Docker daemon
      - "./traefik.yml:/etc/traefik/traefik.yml" # Optional: Traefik static configuration file
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)" # Define a router for the Traefik dashboard
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - proxy

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5444/udp"
    volumes:
      - ./adguard/workdir:/opt/adguardhome/work
      - ./adguard/confdir:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Malta
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
    networks:
      - proxy

  plex:
    image: plexinc/pms-docker
    container_name: plex-server
    restart: on-failure
    volumes:
      - e:/docker/media/plex/config:/config
      - e:/docker/media/plex/transcode:/transcode
      - e:/docker/media/plex/media:/media
    environment:
      - "TZ=Europe/Stockholm"
      - "PLEX_CLAIM=claim-_nxFhTDtyFUeLaLhCE9z"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.rule=Host(`plex.local`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    volumes:
      - e:/docker/media/transmission/config:/config
      - e:/docker/media/transmission/watch:/watch
      - e:/docker/media/plex/media/movies:/downloads
    ports:
      - "9091:9091"
    networks:
      - proxy
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=web"
      - "traefik.http.routers.torrent.rule=Host(`transmission.local`)"
      - "traefik.http.services.torrent.loadbalancer.server.port=9091"

  actualbudget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    ports:
      - "5006:5006"
    networks:
      - proxy
    volumes:
      - e:/docker/actualbudget/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actualbudget.entrypoints=web"
      - "traefik.http.routers.actualbudget.rule=Host(`actuals.local`)"
      - "traefik.http.services.actualbudget.loadbalancer.server.port=5006"

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - e:/docker/homarr/configs:/app/data/configs
      - e:/docker/homarr/icons:/app/public/icons
      - e:/docker/homarr/data:/data
    ports:
      - "7575:7575"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.entrypoints=web"
      - "traefik.http.routers.homarr.rule=Host(`homarr.local`)"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"

networks:
  proxy:
    external: true
