services:
  #budget tools
  actualbudget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    pull_policy: always
    restart: unless-stopped
    ports:
      - "5006:5006"
    networks:
      - proxy
    volumes:
      - ${BASE_PATH}/actualbudget/data:/data
    depends_on:
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actualbudget.entrypoints=web"
      - "traefik.http.routers.actualbudget.rule=Host(`actuals.local`)"
      - "traefik.http.services.actualbudget.loadbalancer.server.port=5006"
  #photo web apps
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    container_name: photoprism
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - proxy
    ports:
      - 2342:2342
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "admin"
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_SITE_URL: "http://photoprism.local"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "My Clan"
      PHOTOPRISM_SITE_AUTHOR: "Prasanna Prabhakaran"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"
      PHOTOPRISM_SIDECAR_JSON: "true"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_THUMB_FILTER: "lanczos"
      PHOTOPRISM_THUMB_UNCACHED: "false"
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680
      PHOTOPRISM_JPEG_SIZE: 7680
      PHOTOPRISM_JPEG_QUALITY: 92
      PHOTOPRISM_DARKTABLE_PRESETS: "false"
    volumes:
      - "${BASE_PATH}/photoprism/storage:/photoprism/storage"
      - "${BASE_PATH}/photoprism/Pictures:/photoprism/originals"
      - "${BASE_PATH}/photoprism/Family:/photoprism/originals/Family"
      - "${BASE_PATH}/photoprism/Friends:/photoprism/originals/Friends"
      - "${BASE_PATH}/photoprism/Import:/photoprism/import"
    depends_on:
      - mariadb
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.entrypoints=web"
      - "traefik.http.routers.photoprism.rule=Host(`photoprism.local`)"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
  #media sharing apps
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/transmission/config:/config
      - ${BASE_PATH}/transmission/watch:/watch
      - ${BASE_PATH}/plex/media/movies:/downloads
    ports:
      - "9091:9091"
    networks:
      - proxy
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC"
    depends_on:
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=web"
      - "traefik.http.routers.torrent.rule=Host(`transmission.local`)"
      - "traefik.http.services.torrent.loadbalancer.server.port=9091"

  plex:
    image: plexinc/pms-docker
    container_name: plex-server
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${BASE_PATH}/plex/media:/media
      - ${BASE_PATH}/plex/transcode:/transcode
    environment:
      - "TZ=Europe/Stockholm"
      - "PLEX_CLAIM=claim-_nxFhTDtyFUeLaLhCE9z"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - proxy
    depends_on:
      - traefik
      - adguardhome
      - transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.rule=Host(`plex.local`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - proxy
    volumes:
      - ${BASE_PATH}/radarr/data:/config
      - ${BASE_PATH}/radarr/download-client-downloads:/downloads
      - ${BASE_PATH}/plex/media/movies:/movies
    ports:
      - 7878:7878
    depends_on:
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${BASE_PATH}/airsonic/config:/config
      - ${BASE_PATH}/airsonic/music:/music
      - ${BASE_PATH}/airsonic/playlists:/playlists
      - ${BASE_PATH}/airsonic/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
    depends_on:
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.entrypoints=web"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.local`)"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - 3500:3000
    networks:
      - proxy
    volumes:
      - ${BASE_PATH}/metabase/plugins:/plugins
      - ${BASE_PATH}/metabase-data:/metabase-data
    depends_on:
      - traefik
      - adguardhome
      - postgres-db
    environment:
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=Welc0me123"
      - "MB_DB_HOST=postgres-db"
    links:
      - traefik
      - adguardhome
      - postgres-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.entrypoints=web"
      - "traefik.http.routers.metabase.rule=Host(`metabase.local`)"
      - "traefik.http.services.metabase.loadbalancer.server.port=3500"
        # - "traefik.http.routers.metabase.tls.certresolver=le"

  thunderbird:
    image: kebles/wanderbird
    container_name: Thunderbird
    ports:
      - "3800:3000"
    networks:
      - proxy
    volumes:
      - ${BASE_PATH}/thunderbird/config:/home/kebles/mail/
    restart: unless-stopped
    links:
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thunderbird.entrypoints=web"
      - "traefik.http.routers.thunderbird.rule=Host(`email.local`)"
      - "traefik.http.services.thunderbird.loadbalancer.server.port=3800"
        # - "traefik.http.routers.metabase.tls.certresolver=le"

  jira:
    image: atlassian/jira-software
    container_name: jira
    ports:
      - 9080:9080
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.entrypoints=web"
      - "traefik.http.routers.jira.rule=Host(`jira.local`)"
      - "traefik.http.services.jira.loadbalancer.server.port=9080"
        # - "traefik.http.routers.metabase.tls.certresolver=le"
