services:
  #base
  traefik:
    extends:
      file: docker-compose.base.yml
      service: traefik
  adguardhome:
    extends:
      file: docker-compose.base.yml
      service: adguardhome

  #services
  actualbudget:
    extends:
      file: docker-compose.services.yml
      service: actualbudget
  transmission:
    extends:
      file: docker-compose.services.yml
      service: transmission
  plex:
    extends:
      file: docker-compose.services.yml
      service: plex
#networks
networks:
  proxy:
    external: true
