 services:
  mariadb:
      image: mariadb:latest
      container_name: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: sa@123
        MYSQL_DATABASE: bitnami_jasperreports
        MYSQL_USER: bn_jasperreports
        MYSQL_PASSWORD:
      ports:
        - "3306:3306"
      networks:
        - proxy
      volumes:
        - e:/docker/mariadb/data:/var/lib/mysql

    jasperreports:
      image: docker.io/bitnami/jasperreports:latest
      ports:
        - "9002:8080"
      volumes:
        - "e:/docker/jasperreports/data:/bitnami/jasperreports"
      # The line below allows you to provide your own JasperReports configuration files, to be copied to WEB-INF
      # - "./config:/bitnami/jasperreports-mounted-conf"
      networks:
        - proxy
      depends_on:
        - mariadb
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - JASPERREPORTS_DATABASE_HOST=mariadb
        - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
        - JASPERREPORTS_DATABASE_USER=bn_jasperreports
        - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports

  networks:
    proxy:
      external: true