version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 443:443/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
        # WebUI
      - 8081:8081/tcp
    networks:
      - traefik-network
    restart: unless-stopped
    volumes:
      - "C:/docker/adguard/conf:/opt/adguardhome/conf"
      - "C:/docker/adguard/work:/opt/adguardhome/work"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=insecure"
      - "traefik.http.routers.adguard.rule=Host(`adguard.docker.localhost`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=8081"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"

networks:
  traefik-network:
    external: true
