version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      # DNS
      - 53:53
        # # DHCP server
        # - 67:67/udp
        # - 68:68/udp
        # HTTPS/DNS-over-HTTPS
      - 443:443/tcp
        # DNS-over-TLS
      - 853:853/tcp
        # DNS-over-QUIC
      - 853:853/udp
        # DNSCrypt
      - 5443:5443/tcp
      - 5443:5443/udp
        # WebUI
      - 3000:3000/tcp
    networks:
      - traefik-network
    restart: unless-stopped
    volumes:
      - "C:/docker/adguard/conf:/opt/adguardhome/conf"
      - "C:/docker/adguard/work:/opt/adguardhome/work"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=insecure"
      - "traefik.http.routers.adguard.rule=Host(`adguard.docker.localhost`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"

networks:
  traefik-network:
    external: true
