services:
  consul:
    image: consul:1.15.4
    container_name: consul
    volumes:
      - consul-data:/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: >
      agent -server -bootstrap -ui -client=0.0.0.0
      -bind=0.0.0.0
      -advertise=192.168.0.65
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  consul-data:
