version: '3.8'

networks:
  # Network for infrastructure
 
  # docker network create --driver bridge katalyst.infra
  # docker network create --driver bridge katalyst.microServices
  # docker network create --driver bridge katalyst.gatewayServices
  default:
    name: katalyst.infra
    external: true

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    restart: on-failure
    volumes:
    - consul-data:/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

volumes:
  consul-data: