---
version: "2"
services:
  ampache:
    image: ampache/ampache
    # image: ampache/ampache:develop # dev branch
    networks:
      - traefik-network
    volumes:
      - $MEDIA_FOLDER:/media:ro
      - ampache-config:/var/www/config
    # ports:
    #   - 80:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ampache.entrypoints=insecure"
      - "traefik.http.routers.ampache.rule=Host(`ampache.docker.localhost`)"
      - "traefik.http.services.ampache.loadbalancer.server.port=80"
      # - "traefik.http.routers.ampache.tls.certresolver=le"

networks:
  traefik-network:
    external: true

volumes:
  ampache-config:
