---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK=022 #optional
    volumes:
      - ./config:/config
      - e:/docker-images-data/jellyfin/data:/data/
      # - $TVSERIES_FOLDER:/data/tvshows
      - e:/docker-images-data/plex/media/movies:/data/movies
      # - $CONCERTS_FOLDER:/data/concerts
      # - /path for transcoding:/transcode #optional
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
    #   - 8920:8920 #optional
    # devices:
    #   - /dev/dri:/dev/dri #optional
    #     # - /dev/vchiq:/dev/vchiq #optional
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      # - "traefik.http.routers.jellyfin.tls.certresolver=le"

networks:
  proxy:
    external: true
