version: '3.8'

networks:
  # Network for infrastructure
  # docker network create --driver bridge KatalystInfraNetwork

  # docker network create --driver bridge katalyst.infra
  # docker network create --driver bridge katalyst.microServices
  # docker network create --driver bridge katalyst.gatewayServices
  default:
    name: katalyst.infra
    external: true

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-mq-server
    restart: on-failure
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
    ports:
     - "5672:5672"
     - "8081:15672"