services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    container_name: photoprism
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - proxy
    ports:
      - 2342:2342
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "admin"
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_SITE_URL: "http://photoprism.local"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "My Clan"
      PHOTOPRISM_SITE_AUTHOR: "Prasanna Prabhakaran"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"
      PHOTOPRISM_SIDECAR_JSON: "true"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_THUMB_FILTER: "lanczos"
      PHOTOPRISM_THUMB_UNCACHED: "false"
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680
      PHOTOPRISM_JPEG_SIZE: 7680
      PHOTOPRISM_JPEG_QUALITY: 92
      PHOTOPRISM_DARKTABLE_PRESETS: "false"
    volumes:
      - "${BASE_PATH}/photoprism/storage:/photoprism/storage"
      - "${BASE_PATH}/photoprism/Pictures:/photoprism/originals"
      - "${BASE_PATH}/photoprism/Family:/photoprism/originals/Family"
      - "${BASE_PATH}/photoprism/Friends:/photoprism/originals/Friends"
      - "${BASE_PATH}/photoprism/Import:/photoprism/import"
    depends_on:
      - mariadb
      - traefik
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.entrypoints=web"
      - "traefik.http.routers.photoprism.rule=Host(`photoprism.local`)"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-photodb
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Welc0me$$
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  proxy:
    external: true
