services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - proxy
    volumes:
      - e:/docker/distributed-cache/redis/data:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.entrypoints=web"
      - "traefik.http.routers.redis.rule=Host(`redis.local`)"
      - "traefik.http.services.redis.loadbalancer.server.port=6379"

networks:
  proxy:
    external: true
